### PR TITLE
Ensure space children comparison is transitive

### LINKED ISSUE #5783: Panic because sorting function doesn't implement total order
We seem to have a panic in the codebase because one of the functions we pass to `sort_by()` doesn't implement a total order.

A sentry report was sent to use with the following message:

```
user-provided comparison function does not correctly implement a total order
```

Sadly the stack trace doesn't really tell us much which function in our codebase called the sorting function.

I attempted to guess which one it could have been in https://github.com/matrix-org/matrix-rust-sdk/pull/5782 but the `recency` sorter seems to be fine.

### PR DESCRIPTION
**Pull request by poljar**
A review commit by commit is most helpful. The majority of this PR introduces small refactors to make it easier to property test the two comparison functions we have in the spaces module.

A bunch of property tests were added to ensure that the comparison functions produce a total order.

In the case of the space children comparison function this wasn't true. The actual fix is contained in 7379e40a, which also has a longer description to explain what's going on.

This closes #5783.

### CODE REVIEW

File: crates/matrix-sdk-ui/src/spaces/mod.rs [hunk 1]
```diff
@@ -647,7 +639,10 @@ impl SpaceService {
                         let a_state = space_child_states.get(&a.room_id).cloned();
                         let b_state = space_child_states.get(&b.room_id).cloned();
 
-                        SpaceRoom::compare_rooms(a, b, a_state, b_state)
+                        SpaceRoom::compare_rooms(
```
Comment (andybalaam) [inline crates/matrix-sdk-ui/src/spaces/mod.rs:642]: Is this part in the wrong commit? I don't see a change to the interface of this function here.

**Review by andybalaam — APPROVED** [review]
Thank you, the separate commits made this easy to review and very clear to understand.

One bit of diff made its way into the wrong commit but otherwise good to go.

File: crates/matrix-sdk-ui/src/spaces/mod.rs (hunk 1 above)
Comment (poljar) [reply crates/matrix-sdk-ui/src/spaces/mod.rs:642]: Oh indeed, thanks for checking this a `jj split` gone wrong.

This one won't compile, it needs to got into `SpaceRoom` refactor commit. Will move this.

Comment (poljar) [reply crates/matrix-sdk-ui/src/spaces/mod.rs:642]: Solved and force-pushed to rewrite the history.

Also, checked that every commit compiles.
