### PR TITLE
fix(sdk): Remove `Deref` impl for `SlidingSyncRoom`

### LINKED ISSUE #1476: Remove `SlidingSyncRoom::deref -> Inner`
Despite `timeline` being non-pub on `SlidingSyncRoom`:

```rust
// Room info as giving by the SlidingSync Feature.
#[derive(Debug, Clone)]
pub struct SlidingSyncRoom {
    client: Client,
    room_id: OwnedRoomId,
    inner: v4::SlidingSyncRoom,
    is_loading_more: Mutable<bool>,
    is_cold: Arc<AtomicBool>,
    prev_batch: Mutable<Option<String>>,
    timeline: AliveRoomTimeline,
}
```

you can call `room.timeline`, which will compile and always have an empty `Vec` in there. That is _super confusing_ and a terrible foot gun, as the `Deref` implemented on `SlidingSyncRoom` puts that through to `inner`, which holds the latest `v4::SlidinSyncRoom` we've received from the server - aside from that we reset its `timeline = vec![]` when we processed the event to prevent them being confusing. However, because of that deref it is still confusing. We should remove the `Deref` instead expose all the fields we actually want to keep either directly on the `SlidingSyncRoom` or at least through getter functions on it.

### PR DESCRIPTION
**Pull request by Hywan**
This implementation is wrong in the sense of its semantics is not about dereferencing a thin pointer to something, but just to give access to one specific field of the entire structure. That's not how `Deref` is supposed to be used.

Moreover, it creates conflict between the `SlidingSyncRoom.timeline` field, and `SlidingSyncRoom.inner.timeline` field, which both exist, but not for the same purposes. It creates confusion in the code.

Finally, it's better to expose proper getters to the outside world, so that we control _and_ test _and_ know exactly what API we provide.

---

* Fix #1476

### CODE REVIEW

File: crates/matrix-sdk/src/sliding_sync.rs [hunk 1]
```diff
@@ -275,6 +278,26 @@ impl SlidingSyncRoom {
         self.inner.name.as_deref()
     }
 
+    /// Is this a direct message?
+    pub fn is_dm(&self) -> Option<bool> {
+        self.inner.is_dm
+    }
+
+    /// Was this an initial response.
+    pub fn is_an_initial_response(&self) -> Option<bool> {
```
Comment (jplatte) [inline crates/matrix-sdk/src/sliding_sync.rs:287]:
```suggestion
    pub fn is_initial_response(&self) -> Option<bool> {
```

or just `is_initial` like in the FFI crate?

Comment (Hywan) [reply crates/matrix-sdk/src/sliding_sync.rs:287]: I don't believe it conveys a good idea of what the method does :-/. “Is it an initial sliding sync room?” would be the first understanding of this, don't you think?

Comment (Hywan) [reply crates/matrix-sdk/src/sliding_sync.rs:287]: Ah sorry, missed it. Yeah, perfect :-)!

**Review by jplatte — APPROVED** [review]
