### PR TITLE
fix(sdk): Aggregate reactions locally

### LINKED ISSUE #1310: Revoke emoji reaction
Event ID is needed to revoke emoji reaction about message.
But reactions of timeline event doesn't support event id to redact that reaction event.
I wonder how user can revoke his reaction about a message.

### LINKED ISSUE #1311: Display more than 5 items of reaction
`BundledReactions` always returns up to 5 reaction items.
I wonder if Synapse server limits query result to 5 items.

### LINKED ISSUE #1312: Senders of ReactionDetails always is unavailable
`TimelineDetails::Ready()` always returns empty senders.
`senders` of reaction is not ready to use yet?
https://github.com/matrix-org/matrix-rust-sdk/blob/c215ac1f4b0b9ecb029ebc0ee73a0959c1ea30e8/crates/matrix-sdk/src/room/timeline/event_item.rs#L393-L409

### PR DESCRIPTION
**Pull request by zecakeh**
The bundled reactions don't have enough data to be usable without extra requests, although we likely have all the necessary data available locally (for now at least as we always start from the end of the timeline).

Tested locally in Fractal.

Fixes #1310.\
Fixes #1311.\
Fixes #1312.

Signed-off-by: Kévin Commaille <zecakeh@tedomum.fr>

### CODE REVIEW

File: crates/matrix-sdk/src/room/timeline/event_item.rs [hunk 1]
```diff
@@ -404,58 +403,34 @@ impl From<RoomEncryptedEventContent> for EncryptedMessage {
...
-    pub complete: bool, // FIXME: Unclear whether this is needed
-
-    /// The reactions.
+    /// The reactions grouped by key.
     ///
     /// Key: The reaction, usually an emoji.\
-    /// Value: The count.
-    pub bundled: IndexMap<String, ReactionDetails>,
+    /// Value: The group of reactions.
+    pub bundled: IndexMap<String, ReactionGroup>,
```
Comment (jplatte) [inline crates/matrix-sdk/src/room/timeline/event_item.rs:412]: If this struct has only a single field, maybe it isn't needed at all? Could be a type alias `type BundledReactions = IndexMap<String, ReactionGroup>;` instead.

Comment (zecakeh) [reply crates/matrix-sdk/src/room/timeline/event_item.rs]: You're right. I've been hesitating in case we need more fields in the future (e.g. when server-side aggregation is more usable), but we can always change it later.

File: crates/matrix-sdk/tests/integration/room/timeline.rs [hunk 2]
```diff
@@ -419,10 +419,11 @@ async fn reaction() {
...
     assert_eq!(event_item.reactions().len(), 1);
-    let details = &event_item.reactions()["👍"];
-    assert_eq!(details.count, uint!(1));
-    let senders = assert_matches!(&details.senders, TimelineDetails::Ready(s) => s);
-    assert_eq!(*senders, vec![user_id!("@bob:example.org").to_owned()]);
+    let group = &event_item.reactions()["👍"];
+    assert_eq!(group.len(), 1);
+    let mut senders = group.senders();
+    assert_eq!(senders.next(), Some(user_id!("@bob:example.org")));
+    assert_eq!(senders.next(), None);
```
Comment (jplatte) [inline crates/matrix-sdk/tests/integration/room/timeline.rs:426]:
```suggestion
    let senders: Vec<_> = group.senders().collect();
    assert_eq!(senders.as_slice(), [user_id!("@bob:example.org")]);
```

**Review by jplatte — APPROVED** [review]

File: bindings/matrix-sdk-ffi/src/timeline.rs [hunk 3]
```diff
@@ -250,7 +250,7 @@ impl EventTimelineItem {
                 remote_event_item
                     .reactions()
                     .iter()
-                    .map(|(k, v)| Reaction { key: k.to_owned(), count: v.count.into() })
```
Comment (Hywan) [inline bindings/matrix-sdk-ffi/src/timeline.rs:253]: It's still a better idea to `.try_into().unwrap()` to avoid surprises.
Well, here it's a `usize` to `u64`, so it's unlikely to be broken, but still :-).

File: crates/matrix-sdk/src/room/timeline/event_item.rs [hunk 4]
```diff
@@ -490,58 +489,33 @@ impl From<RoomEncryptedEventContent> for EncryptedMessage {
...
-                (a.annotation_type == AnnotationType::Reaction).then(|| {
-                    let details =
-                        ReactionDetails { count: a.count, senders: TimelineDetails::Unavailable };
-                    (a.key, details)
-                })
-            })
-            .collect();
+/// The reactions grouped by key.
+///
+/// Key: The reaction, usually an emoji.\
```
Comment (Hywan) [inline crates/matrix-sdk/src/room/timeline/event_item.rs:494]:
```suggestion
/// Key: The reaction, usually an emoji.
///
```

?

File: crates/matrix-sdk/src/room/timeline/event_item.rs [hunk 5]
```diff
@@ -490,58 +489,33 @@ impl From<RoomEncryptedEventContent> for EncryptedMessage {
...
+/// Value: The group of reactions.
+pub type BundledReactions = IndexMap<String, ReactionGroup>;
 
-        BundledReactions { bundled, complete: ann.next_batch.is_none() }
-    }
-}
+/// A group of reaction events on the same event with the same key.
+///
+/// This is a map of the timeline key of the reaction to the ID of the sender of
```
Comment (Hywan) [inline crates/matrix-sdk/src/room/timeline/event_item.rs:500]: Timeline key has been removed. Can you update the comment please :-)?

Comment (Hywan) [inline crates/matrix-sdk/src/room/timeline/event_item.rs:500]:
```suggestion
/// This is a map of the timeline key of the reactions to the ID of the sender of
```

File: crates/matrix-sdk/src/room/timeline/inner.rs [hunk 6]
```diff
@@ -51,6 +52,8 @@ pub(super) struct TimelineInnerMetadata {
     // Reaction event / txn ID => sender and reaction data
     pub(super) reaction_map:
         HashMap<(Option<OwnedTransactionId>, Option<OwnedEventId>), (OwnedUserId, Annotation)>,
+    // ID of event that is not in the timeline yet => List of reaction event / txn ID
```
Comment (Hywan) [inline crates/matrix-sdk/src/room/timeline/inner.rs:55]:
```suggestion
    /// ID of event that is not in the timeline yet => List of reaction event / txn ID
```

**Review by Hywan — CHANGES_REQUESTED** [review]
A few comments, apart from that, good work, thanks!

File: crates/matrix-sdk/src/room/timeline/event_item.rs (hunk 4 above)
Comment (zecakeh) [reply crates/matrix-sdk/src/room/timeline/event_item.rs:494]: If you want, it's just that with this syntax it doesn't create a new paragraph between the sentences, it's just a line break.
