### PR TITLE
use hoist_and_deserialize for state events

### LINKED ISSUE #292: SyncStateEvent::membership_change() not working with synapse
**Describe the bug**
Because synapse tosses prev_content into unsigned now and then SyncStateEvent::membership_change() isn't working as expected

**To Reproduce**
Change your displayname, the corresponding `event.membership_change()` will think you joined the room

**Expected behavior**
It should not think you joined the room

poljar mentioned using https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk_base/src/client.rs#L102 over here https://github.com/matrix-org/matrix-rust-sdk/blob/master/matrix_sdk/src/event_handler/mod.rs#L94 however that doesn't seem to be the only location where such deserialization happens, e.g. in the timeline block of sync responses.

### PR DESCRIPTION
**Pull request by Sorunome**
Fixes #292 

Signed-Off-By: Sorunome <mail@sorunome.de>

### CODE REVIEW

File: matrix_sdk_base/src/client.rs [hunk 1]
```diff
@@ -129,7 +129,7 @@ fn hoist_member_event(
     Ok(e)
 }
 
-fn hoist_room_event_prev_content(
+pub fn hoist_room_event_prev_content(
```
Comment (poljar) [inline matrix_sdk_base/src/client.rs:132]: This will now need docs since it's public, you can mostly copy them from the other methods.

**Review by poljar — CHANGES_REQUESTED** [review]
Looks sensible, please just add some docs to the newly public method.
