### PR TITLE
fix(sdk): `Client::sync_once` defaults to reuse previous token

### LINKED ISSUE #1835: `sync_once` does not use `client.sync_token`
As `Client::sync_token` is private, and `Client::sync_once` [does not fall back to it](https://github.com/matrix-org/matrix-rust-sdk/blob/cbfa1340875d9d5ceec718fc1fd6a8e23ad47810/crates/matrix-sdk/src/client/mod.rs#L2167) when no sync token is provided, it's not possible to use `sync_once` with a client's remembered sync token.

I assume since `Client::sync_with_result_callback` [does fall back to the client's `sync_token`](https://github.com/matrix-org/matrix-rust-sdk/blob/cbfa1340875d9d5ceec718fc1fd6a8e23ad47810/crates/matrix-sdk/src/client/mod.rs#L2403-L2405), that this behaviour is likely also intended for `sync_once`.

It's an easy fix, but I thought I should open an issue as I'm not sure what the intended behaviour is (i.e. should `sync_token` be made public again? or should `sync_once` fall back to `sync_token` when a token isn't provided)

### PR DESCRIPTION
**Pull request by dragonfly1033**
Fixes #1835.

Introduces a new `SyncToken` enum for the `SyncSettings::token` field.
The enum has 3 variants: ReusePrevious (default), NoToken, Specific(String).

Some tests were changed to use the old default (NoToken).

Signed-off-by: Shrey Patel shreyp@element.io

### CODE REVIEW

File: crates/matrix-sdk/src/client/mod.rs [hunk 1]
```diff
@@ -2604,8 +2610,8 @@ impl Client {
         let mut timeout = None;
         let mut last_sync_time: Option<Instant> = None;
 
-        if sync_settings.token.is_none() {
-            sync_settings.token = self.sync_token().await;
+        if let SyncToken::NoToken = sync_settings.token {
+            sync_settings.token = SyncToken::from_optional_token(self.sync_token().await);
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/client/mod.rs]: This is incorrect, as it would inhibit the use of a custom token. I think you'd need the same code chunk as 2307 -> 2311, so maybe we could factor this into a small helper function and reuse it here.

File: crates/matrix-sdk/src/config/sync.rs [hunk 2]
```diff
@@ -19,14 +19,45 @@ use ruma::{api::client::sync::sync_events, presence::PresenceState};
 
 const DEFAULT_SYNC_TIMEOUT: Duration = Duration::from_secs(30);
 
+/// Token to use in [`SyncSettings`]
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/config/sync.rs]:
```suggestion
/// Token to be used in the next sync request.
```

File: crates/matrix-sdk/src/config/sync.rs [hunk 3]
```diff
@@ -19,14 +19,45 @@ use ruma::{api::client::sync::sync_events, presence::PresenceState};
...
+#[derive(Clone, Default, Debug)]
+pub enum SyncToken {
+    /// Provide a specific token
+    Specific(String),
+    /// Provide no token
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/config/sync.rs]:
```suggestion
    /// Enforce no tokens at all.
```

File: crates/matrix-sdk/src/config/sync.rs [hunk 4]
```diff
@@ -19,14 +19,45 @@ use ruma::{api::client::sync::sync_events, presence::PresenceState};
 
 const DEFAULT_SYNC_TIMEOUT: Duration = Duration::from_secs(30);
 
+/// Token to use in [`SyncSettings`]
+#[derive(Clone, Default, Debug)]
+pub enum SyncToken {
+    /// Provide a specific token
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/config/sync.rs]:
```suggestion
    /// Provide a specific token.
```

File: crates/matrix-sdk/src/config/sync.rs [hunk 5]
```diff
@@ -19,14 +19,45 @@ use ruma::{api::client::sync::sync_events, presence::PresenceState};
...
+    Specific(String),
+    /// Provide no token
+    NoToken,
+    /// Use previous token
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/config/sync.rs]:
```suggestion
    /// Use a previous token if the client saw one in the past, and none otherwise.
    ///
    /// This is the default value.
```

File: crates/matrix-sdk/src/config/sync.rs [hunk 6]
```diff
@@ -19,14 +19,45 @@ use ruma::{api::client::sync::sync_events, presence::PresenceState};
...
+}
+
+impl<T> From<T> for SyncToken
+where
+    T: Into<String>,
+{
+    fn from(token: T) -> SyncToken {
+        SyncToken::Specific(token.into())
+    }
+}
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/config/sync.rs:44]: Nice trick to avoid changing the public API :sunglasses:

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Looks great, thanks for fixing this! Can you add an entry in the `matrix_sdk`'s `CHANGELOG.md`, please? (in the `refactor` section, with an annotation that it's a breaking change)

File: crates/matrix-sdk/src/config/sync.rs (hunk 6 above)
Comment (dragonfly1033) [reply crates/matrix-sdk/src/config/sync.rs:44]: Thanks, I was pleased with that too

File: crates/matrix-sdk/src/client/mod.rs (hunk 1 above)
Comment (zecakeh) [reply crates/matrix-sdk/src/client/mod.rs]: Shouldn't this be dropped actually? All sync methods call `sync_loop_helper` which calls `sync_once` in turn, which now supports reading the sync token by default.

That said, it's a bit of a potential footgun to set `SyncToken::NoToken` in a loop.

Comment (dragonfly1033) [reply crates/matrix-sdk/src/client/mod.rs]: I'm not sure about this. The original code was checking if the token is None and re-using the old token if so. This is the behaviour described by the ReusePrevious variant which we could decode into a value using the code snippet you mention in 2307-2311 but that does `SyncToken -> Option<String>` whereas here we need `Option<String> -> SyncToken`. 

It seems that what was intended here is to enforce what we now have as the `ReusePrevious` behaviour. To that effect, I suggest specifying this in all the places in which this function is called and deleting this block (as the destructuring happens in `sync_once` which this function calls). 

Note that since `ReusePrevious` is now the default I only have to change it if it is not using default.
Another note that if the token is `Specific` then there's no behaviour change by doing this (I think) which is good.

Comment (dragonfly1033) [reply crates/matrix-sdk/src/client/mod.rs]: Perhaps a better explanation: 
The original method received `None` which could be interpreted as `NoToken` or `ReusePrevious`. 
Based on the original code, I conclude that `ReusePrevious` was intended.
This is the default so no action is required. 
Which leaves the question of what to do if I receive `NoToken`?
Either I can enforce `ReusePrevious` and pass that on (which is what my current code does)
Or I can pass on the `NoToken` unchanged. This would be new behaviour as `NoToken` is a new state.

Comment (bnjbvr) [reply crates/matrix-sdk/src/client/mod.rs]: Ah, I see what you mean.

Well, it seems that this API is kind of badly designed anyways. In the version before this PR: if you set the `SyncSettings::token()`, then it would be reused for all the sync updates below, since it's the same one all the time. Which is nonsensical; if you always sync with the same token, the server will respond with the same response :exploding_head: 

The problem you've found here is a generalization of this issue, that now applies to `NoToken` as well. The `SyncSettings::token` should only be applied to the first sync.

So I think a better way to go would be:

- do nothing with the `sync_settings.token` before the async stream
- move the `is_first_sync = false;` statement after the `yield` statement (line 2637)
- between the `yield` statement and the `is_first_sync = false` statement, if `is_first_sync`, set `sync_settings.token` to `ReusePrevious` (must happen after the `sync_loop_helper` call).

This way, the original intent would be preserved: only apply the token to the first sync.

1. With that change, I wonder if some of the tests would not require the changes you've made? Might be worth trying it out by moving all the test-related changes into a separate commit (`git rebase -i` is your friend, or `lazygit` is your best friend), then revert it, and see how many tests now fail.
2. You get bonus points if you can write a regression test that would show that, without the changes from this PR, the client would use the same token all the time if `sync_once()` is called with a `Settings::sync_token` set to `Some`, proving my theory above correct :)

How does that sound?

Comment (dragonfly1033) [reply crates/matrix-sdk/src/client/mod.rs]: This explains a lot, I did notice that the problem seemed to arise when syncing multiple times. I had set `NoToken` for every call to `sync_once` but this would imply that only those after the first would have needed it.

Comment (zecakeh) [reply crates/matrix-sdk/src/client/mod.rs]: The code before this PR actually always overwrites the token after a sync in `sync_loop_helper`, so it seems like it is doing the right thing.

Comment (zecakeh) [reply crates/matrix-sdk/src/client/mod.rs]: And this still applies in this PR, so there should actually be no problem and this can be removed. The `SyncToken` setting is only used for the first sync anyway.

Comment (bnjbvr) [reply crates/matrix-sdk/src/client/mod.rs]: Ah yeah, Kevin's right :+1: So maybe we can just get rid of this initial statement, and add a comment below that the sync settings will be overwritten in `sync_loop_helper`.

(No need to try to write a regression test either, of course.)

> This explains a lot, I did notice that the problem seemed to arise when syncing multiple times. I had set NoToken for every call to sync_once but this would imply that only those after the first would have needed it.

I think the tests are kinda wrong; they should not `clone` the `SyncSettings` :sweat_smile: But let's not worry about it too much for today :)

File: crates/matrix-sdk/src/config/sync.rs (hunk 2 above)
Comment (bnjbvr) [reply crates/matrix-sdk/src/config/sync.rs]: Hmm, I think this comment and the few below have not been addressed yet, right?

Comment (dragonfly1033) [reply crates/matrix-sdk/src/config/sync.rs]: :sob:  I forgot to pop from stash

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Just missing a `CHANGELOG.md` entry, and we'll be good to go :party

**Review by bnjbvr — APPROVED** [review]
Thank you :partying_face:
