### PR TITLE
Fix a race condition in the redecryptor leading to missed decryption attempts

### LINKED ISSUE #5474: UTDs not retried when key arrives at almost the same time
### Steps to reproduce

See this rageshake: https://github.com/element-hq/element-x-android-rageshakes/issues/4076

The logs in the receiver side show a pattern like this:

```
2025-01-20T15:46:43.519041Z Failed to decrypt a room event
... (9 more Failed to decrypt)
2025-01-20T15:46:46.398276Z Failed to decrypt a room event
2025-01-20T15:46:46.407885Z Received a new megolm room key
2025-01-20T15:46:46.418528Z Failed to decrypt a room event
.. (2 more Failed to decrypt)
```

So the megolm key arrived at almost the same moment as the events.

There is no mention of "Retrying decryption" anywhere in the receiver logs.

I am wondering whether the async task pulling from `room_keys_received_stream()` might have retried decryption too early, before the incoming batch of events was finished processing?

### PR DESCRIPTION
**Pull request by poljar**
This PR fixes a race condition in the redecryptor.

Namely, events and room keys are received over two different sync streams from the homeserver. When events are received over the sync, we first try to decrypt them, this might fail because the room key hasn't yet arrived over the other sync stream. The event cache will then persist the event as a UTD.

At the same time, the redecryptor will listen to room keys that arrive on the other sync stream. Once the redecryptor gets notified about a room key, it will attempt to fetch the event from the event cache to decrypt the event and replace it.

Crucially if the key arrives before the event gets persisted but after the initial decryption attempt we might never attempt to redecrypt such an event.

The fix is relatively straightforward, we'd need a synchronization point for the two different tasks, the event cache which adds events and the redecryptor which listens to room keys to decrypt events.

A lock could have been used, so the storing and redecrypting of events becomes synchronized via the storage layer. This approach could have degraded performance since the event cache needs to handle a lot of events.

The approach that was chosen here is to let the redecryptor listen to updates coming from the event cache itself. If the event cache tells us that it persisted a UTD, we will attempt to decrypt. Upon a successful decryption we will replace the event in the cache as well.

A review commit by commit is probably the easiest way to handle this.

This closes #5474.

### CODE REVIEW

**Review by andybalaam — APPROVED** [review]
Looks good. Excited about this fix.

File: crates/matrix-sdk-common/src/linked_chunk/updates.rs [hunk 1]
```diff
@@ -114,6 +114,31 @@ pub enum Update<Item, Gap> {
...
+impl<Item, Gap> Update<Item, Gap> {
+    /// Get the items from the [`Update`] if any.
+    ///
+    /// This function is useful if you only care about the items from the
+    /// [`Update`] and not what kind of update it was and where the items
+    /// should be placed.
+    ///
+    /// [`Update`] variants which don't contain any items will return an empty
+    /// [`Vec`].
+    pub fn into_items(self) -> Vec<Item> {
```
Comment (Hywan) [inline crates/matrix-sdk-common/src/linked_chunk/updates.rs:126]: Makes sense to me.

**Review by Hywan — APPROVED** [review]
Looks good to me. Well done! Finding the race condition was non-trivial…
