### PR TITLE
fix(sdk): Don't overwrite previously added state events for this room in state_event sync processing

### LINKED ISSUE #4952: regular sync: power levels and other state events are missing
Was trying to upgrade to latest `main` when I noticed that asking any room for `power_levels` comes back with `InsufficientData`. We are using regular old sync (are in the process of migrating to sliding sync) and it appears that on latest `main` the state events aren't saved to the state_store anymore.

Some git bisecting points me to db6d1b4cd6893912387867831f069cdc712034a8 being the commit it all breaks with. 

After a brief introspection it seems that there is no new equivalent of the removed state-events adding for non-user-events: https://github.com/matrix-org/matrix-rust-sdk/commit/db6d1b4cd6893912387867831f069cdc712034a8#diff-c559762e72a5a86b43382e9ebb7f1bf5d8144f409c1789ad5bb4294eabf44d07L437-L441 

I'll investigate further and see if I can come up with a patch.

### PR DESCRIPTION
**Pull request by gnunicorn**
Fixes #4952 .

Signed-off-by: Benjamin Kampmann <ben@acter.global>

### CODE REVIEW

**Comment by gnunicorn** [comment]
looks like I have another failure. redoing the change.

**Comment by gnunicorn** [comment]
Okay, this does seem to do the trick now, actually not overwriting the wrong items.

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Thanks, looks sensible; can you write a regression test please?

File: crates/matrix-sdk-base/src/response_processors/state_events.rs [hunk 1]
```diff
@@ -216,3 +213,30 @@ where
...
+    use crate::test_utils::logged_in_base_client;
+
+    #[async_test]
+    async fn test_state_events_after_sync() {
+        // Given a room
+        let user_id = user_id!("@u:u.to");
+
+        let client = logged_in_base_client(Some(user_id)).await;
+
+        let response = sync_response(SyncResponseFile::DefaultWithStateInTimeline);
```
Comment (bnjbvr) [inline crates/matrix-sdk-base/src/response_processors/state_events.rs:231]: Ouch, we try to not use the `SyncResponseFile` anymore, and instead use the glorious `EventFactory`, which makes it more ergonomic to create smaller sync responses. See for instance some usage in tests from this module: https://github.com/matrix-org/matrix-rust-sdk/blob/a81ac262d681fb77444ec94e6c4e9fe03bd794bf/crates/matrix-sdk-base/src/read_receipts.rs#L643-L656

And then let's get rid of the new `DefaultWithStateInTimeline`.

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Thanks; let's try to not use the `SyncResponseFile` anymore (see #3716 for context).

File: crates/matrix-sdk-base/src/response_processors/state_events.rs (hunk 1 above)
Comment (gnunicorn) [reply crates/matrix-sdk-base/src/response_processors/state_events.rs]: ack. I've replaced the last commit with a new one in this format.

**Review by bnjbvr — APPROVED** [review]
Nice, thanks!
