### PR TITLE
fix(base): Handle stripped state events that fail to deserialize

### LINKED ISSUE #2778: State events that fail to deserialize should not be ignored
This is a problem similar to #607: state events that fail to deserialize are ignored.

But usually in the spec a state event that has invalid fields in the content still replaces the previous state event. It is just treated as if there was no state event of that type to begin with.

I believe that's due to servers not having to validate the content of state events outside of state res, so they always treat any accepted state event as the current state.

Examples from the spec:

- For [`m.space.child`](https://spec.matrix.org/v1.8/client-server-api/#mspacechild-relationship):
    > Child rooms can be removed from a space by omitting the `via` key of `content` on the relevant state event, such as through redaction or otherwise clearing the content.
    
    Although the`via` field is now marked as required: https://github.com/matrix-org/matrix-spec/pull/1618.
- For [`m.room.name`](https://spec.matrix.org/v1.8/client-server-api/#mroomname):
    > A room with an `m.room.name` event with an absent, null, or empty name field should be treated the same as a room with no `m.room.name` event.

### PR DESCRIPTION
**Pull request by zecakeh**
This requires https://github.com/ruma/ruma/pull/2353 to be reviewed and merged.

Closes #2778.

We make `RawSyncStateEventWithKeys` generic over the inner enum type, which allows us to share code between stripped and non-stripped rooms, including the code that makes sure that we handle events that fail to deserialize fully.

- [x] I've documented the public API Changes in the appropriate `CHANGELOG.md` files.
- [x] I've read [the `CONTRIBUTING.md` file](https://github.com/matrix-org/matrix-rust-sdk/blob/main/CONTRIBUTING.md), notably the sections about Pull requests, Commit message format, and AI policy.
- [ ] This PR was made with the help of AI.

### CODE REVIEW

File: crates/matrix-sdk-base/src/room/room_info.rs [hunk 1]
```diff
@@ -186,38 +187,40 @@ impl BaseRoomInfo {
...
             (StateEventType::RoomEncryption, "") => {
                 // No redacted or failed deserialization branch - enabling encryption cannot be
                 // undone.
-                if let Some(SyncStateEvent::Original(event)) =
-                    raw_event.deserialize_as(|any_event| {
-                        as_variant!(any_event, AnySyncStateEvent::RoomEncryption)
-                    })
+                if let Some(event) = raw_event.deserialize_as_minimal_event(|any_event| {
+                    as_variant!(any_event, AnyPossiblyRedactedStateEventContent::RoomEncryption)
+                }) && event.content.algorithm.is_some()
```
Comment (andybalaam) [inline crates/matrix-sdk-base/src/room/room_info.rs:201]: So previously if the `m.room.encryption` event was redacted, we would not enter the `if let`, but now, because we allow redacted events to enter the `if let` and be cast using `as_variant`, we need to check explicitly for the case where there is no `algorithm` in their `content`. Did I understand right?

File: crates/matrix-sdk-base/src/room/room_info.rs [hunk 2]
```diff
@@ -186,38 +187,40 @@ impl BaseRoomInfo {
...
     /// Returns true if the event modified the info, false otherwise.
-    pub fn handle_state_event(&mut self, raw_event: &mut RawSyncStateEventWithKeys) -> bool {
+    pub fn handle_state_event<T: AnyStateEventEnum>(
+        &mut self,
+        raw_event: &mut RawStateEventWithKeys<T>,
+    ) -> bool {
         match (&raw_event.event_type, raw_event.state_key.as_str()) {
             (StateEventType::RoomEncryption, "") => {
                 // No redacted or failed deserialization branch - enabling encryption cannot be
                 // undone.
```
Comment (andybalaam) [inline crates/matrix-sdk-base/src/room/room_info.rs]: Could you add to this comment a bit to make it clear that `m.room.encryption` is a special case, and how we are handling it?

File: crates/matrix-sdk-base/src/room/room_info.rs [hunk 3]
```diff
@@ -294,46 +309,58 @@ impl BaseRoomInfo {
...
-                    true
+                    let new_max = i64::from(
+                        event
+                            .content
+                            .users
+                            .values()
+                            .fold(event.content.users_default, |max_pl, user_pl| {
+                                max_pl.max(*user_pl)
+                            }),
+                    );
```
Comment (andybalaam) [inline crates/matrix-sdk-base/src/room/room_info.rs:357]: Can you explain to me why we can't use the `power_levels` method any more? Should it be adapted so it is suitable?

File: crates/matrix-sdk-base/src/room/room_info.rs [hunk 4]
```diff
@@ -852,8 +787,11 @@ impl RoomInfo {
     /// Handle the given stripped state event.
     ///
     /// Returns true if the event modified the info, false otherwise.
-    pub fn handle_stripped_state_event(&mut self, event: &AnyStrippedStateEvent) -> bool {
-        self.base_info.handle_stripped_state_event(event)
+    pub fn handle_stripped_state_event(
+        &mut self,
+        raw_event: &mut RawStateEventWithKeys<AnyStrippedStateEvent>,
+    ) -> bool {
+        self.base_info.handle_state_event(raw_event)
```
Comment (andybalaam) [inline crates/matrix-sdk-base/src/room/room_info.rs:795]: I don't see a test that covers the new behaviour. Did I miss it? If not, please can you add one or more?

**Review by andybalaam — COMMENTED** [review]
As far as I understand it, this looks good, but I'd like @poljar to take a look

File: crates/matrix-sdk-base/src/room/room_info.rs (hunk 1 above)
Comment (zecakeh) [reply crates/matrix-sdk-base/src/room/room_info.rs:201]: Yes, you are right.

File: crates/matrix-sdk-base/src/room/room_info.rs (hunk 3 above)
Comment (zecakeh) [reply crates/matrix-sdk-base/src/room/room_info.rs:357]: This is just more efficient, the `power_levels` method forces us to clone the whole `content`, and asks for other arguments that we don't need to compute this particular value.

File: crates/matrix-sdk-base/src/room/room_info.rs (hunk 4 above)
Comment (zecakeh) [reply crates/matrix-sdk-base/src/room/room_info.rs:795]: Indeed, I forgot to add tests.

File: crates/matrix-sdk-base/src/room/room_info.rs (hunk 2 above)
Comment (zecakeh) [reply crates/matrix-sdk-base/src/room/room_info.rs]: Done in da82370422e85d1f82091f6157fc4706adbca93e.

File: crates/matrix-sdk-base/src/room/room_info.rs (hunk 4 above)
Comment (zecakeh) [reply crates/matrix-sdk-base/src/room/room_info.rs:795]: Done in fb29e228410f1a269b856b79a5f28703be754617.

**Comment by zecakeh** [comment]
Now that the upstream PR has been merged, this requires #6241 to handle other breaking changes upstream.

**Comment by andybalaam** [comment]
Feel free to rebase and force push and give me a ping when it's ready to merge.

**Comment by zecakeh** [comment]
This PR is now rebased on main and ready to be merged.
