### PR TITLE
fix(bindings) Withheld code mapping

### LINKED ISSUE #1806: MissingRoomKey withheldCode binding is returning the human readable string instead of the code
`error.rs`
```
MegolmError::MissingRoomKey(withheld_code) => Self::MissingRoomKey {
                error: "Withheld Inbound group session".to_owned(),
                withheld_code: withheld_code.map(|w| w.to_string()),
            },
```

Expected 
`m.unverified` 

Actual
`The sender has disabled encrypting to unverified devices.`

### PR DESCRIPTION
**Pull request by BillCarsonFr**
Fixes #1806

Withheld error binding was exposing human readable error instead of withheld vcode

### CODE REVIEW

File: bindings/matrix-sdk-crypto-ffi/src/error.rs [hunk 1]
```diff
@@ -93,3 +93,25 @@ impl From<InnerStoreError> for DecryptionError {
...
+
+    #[test]
+    fn test_withheld_error_mapping() {
+        use matrix_sdk_crypto::types::events::room_key_withheld::WithheldCode;
+
+        let inner_error = MegolmError::MissingRoomKey(Some(WithheldCode::Unverified));
+
+        let binding_error: DecryptionError = inner_error.into();
+
+        match binding_error {
```
Comment (poljar) [inline bindings/matrix-sdk-crypto-ffi/src/error.rs:110]: You can use the `assert_matches!()` macro here to get a better error message in case the test fails.

**Review by poljar — CHANGES_REQUESTED** [review]
Let's use `assert_matches!()`, looks good otherwise.

File: bindings/matrix-sdk-crypto-ffi/src/error.rs (hunk 1 above)
Comment (BillCarsonFr) [reply bindings/matrix-sdk-crypto-ffi/src/error.rs]: Oh, I just discovered that it was possible to "capture" the match while doing assert_matches.
updated

**Review by poljar — APPROVED** [review]
