### PR TITLE
fix(ui): Check if an Event is redacted before trying to decrypt it.

### LINKED ISSUE #5796: Notification resolver resolves Redacted Event as EncryptedEvent
Context and more details in https://github.com/element-hq/element-x-android/issues/5569

### PR DESCRIPTION
**Pull request by bmarty**
Check if an Event is redacted before trying to decrypt it.

Use a new enum `NotificationStatus.EventRedacted` when trying to resolve an event for a notification.

PR done with the help of AI: GitHub copilot chat in VisualStudio.

I confirm that the fix is working in EXA with the code in https://github.com/element-hq/element-x-android/pull/6241

Fixes #5796

- [x] I've documented the public API Changes in the appropriate `CHANGELOG.md` files.
- [x] I've read [the `CONTRIBUTING.md` file](https://github.com/matrix-org/matrix-rust-sdk/blob/main/CONTRIBUTING.md), notably the sections about Pull requests, Commit message format, and AI policy.
- [x] This PR was made with the help of AI.

Signed-off-by: benoitm@element.io

### CODE REVIEW

**Comment by bmarty** [comment]
Moving to ready for review. The CI failure does not seems to be related to my changes, but who knows?

**Comment by andybalaam** [comment]
> Moving to ready for review. The CI failure does not seems to be related to my changes, but who knows?

The failures look like an infrastructure problem:

>   /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +2fac12f78ac358bcae3921c0138a47eddfe1e54c:refs/remotes/pull/6203/merge
  Error: fatal: remote error: upload-pack: not our ref 2fac12f78ac358bcae3921c0138a47eddfe1e54c
  The process '/usr/bin/git' failed with exit code 128

I have re-kicked them.

File: crates/matrix-sdk-ui/src/notification_client.rs [hunk 1]
```diff
@@ -797,6 +822,15 @@ fn is_event_encrypted(event_type: TimelineEventType) -> bool {
     is_still_encrypted
 }
 
+fn is_event_redacted(event: &AnySyncTimelineEvent) -> bool {
+    // Check if the event is a message-like event but has no original content (i.e.,
+    // redacted)
+    match event {
+        AnySyncTimelineEvent::MessageLike(msg) => msg.original_content().is_none(),
```
Comment (andybalaam) [inline crates/matrix-sdk-ui/src/notification_client.rs]:
```suggestion
        AnySyncTimelineEvent::MessageLike(msg) => msg.is_redacted(),
```

File: crates/matrix-sdk-ui/src/notification_client.rs [hunk 2]
```diff
@@ -1160,4 +1198,53 @@ mod tests {
...
+        let redacted_event = EventFactory::new()
+            .room(room_id)
+            .sender(user_id!("@sender:b.c"))
+            .redacted(&ALICE, RedactedRoomMessageEventContent::new())
+            .event_id(&event_id)
+            .into_raw_sync();
+        let redacted_bytes = redacted_event.json().get().as_bytes().to_vec();
+        let mut room = v5::response::Room::new();
+        room.timeline =
+            vec![ruma::serde::Raw::from_json(serde_json::from_slice(&redacted_bytes).unwrap())];
```
Comment (andybalaam) [inline crates/matrix-sdk-ui/src/notification_client.rs]: You can use `into_raw` directly:

```
        let redacted_event = EventFactory::new()
            .room(room_id)
            .sender(user_id!("@sender:b.c"))
            .redacted(&ALICE, RedactedRoomMessageEventContent::new())
            .event_id(&event_id)
            .into_raw();
        let mut room = v5::response::Room::new();
        room.timeline = vec![redacted_event];
```

File: crates/matrix-sdk-ui/CHANGELOG.md [hunk 3]
```diff
@@ -58,6 +58,9 @@ All notable changes to this project will be documented in this file.
   the user who forwarded the keys used to decrypt the event as part of an [MSC4268](https://github.com/matrix-org/matrix-spec-proposals/pull/4268)
   key bundle.
   ([#6000](https://github.com/matrix-org/matrix-rust-sdk/pull/6000))
+- [**breaking**] Add `NotificationState.EventRedacted` enum value, to handle the case
+  where a notification resolves to a redacted event.
+  ([#6203](https://github.com/matrix-org/matrix-rust-sdk/pull/6203))
```
Comment (andybalaam) [inline crates/matrix-sdk-ui/CHANGELOG.md]: This should be added at the top of the changelog because it is more recent.

**Comment by bmarty** [comment]
Thanks for the review @andybalaam , I think I have handled all your remarks.
