### PR TITLE
Session verification incoming request support

### LINKED ISSUE #3595: Receiving a verification request does not work
As per https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/session_verification.rs#L153 - you cannot be on the receiving end of a verification request currently.

This means you can't verify your EX device if you only have EX clients.

### PR DESCRIPTION
**Pull request by stefanceriu**
This PR introduced FFI level API support for interacting with incoming session verification requests. Best reviewed commit by commit
- it exposes a new `did_receive_verification_request` `SessionVerificationController` delegate method that includes information about the incoming request/device/sender
- the client can `acknowledge_verification_request` to get informed about it getting accepted somewhere else or cancelled
- the client can also `accept_verification_request` to start interacting with it

This PR also internally switches to the `VerificationRequest::changes` publisher, fixes a couple of invalid VerificationMachine tests and starts storing requesting `DeviceData` directly in `VerificationRequestState. Requested`

Relates to element-hq/element-meta/issues/2464, fixes #3595.

### CODE REVIEW

File: bindings/matrix-sdk-ffi/src/session_verification.rs [hunk 1]
```diff
@@ -60,80 +73,128 @@ pub struct SessionVerificationController {
 
 #[matrix_sdk_ffi_macros::export]
 impl SessionVerificationController {
-    pub async fn is_verified(&self) -> Result<bool, ClientError> {
-        let device =
-            self.encryption.get_own_device().await?.context("Our own device is missing")?;
+    pub fn set_delegate(&self, delegate: Option<Box<dyn SessionVerificationControllerDelegate>>) {
```
Comment (stefanceriu) [inline bindings/matrix-sdk-ffi/src/session_verification.rs:76]: I considered switching away from a delegate and towards a listener but the public api changes are so small that I don't really thing it's worth it at this point. Let's reassess when we start thinking about user verification.

File: crates/matrix-sdk-crypto/src/verification/requests.rs [hunk 2]
```diff
@@ -78,9 +78,9 @@ pub enum VerificationRequestState {
         /// The verification methods supported by the sender.
         their_methods: Vec<VerificationMethod>,
 
-        /// The device ID of the device that responded to the verification
+        /// The device data of the device that responded to the verification
         /// request.
-        other_device_id: OwnedDeviceId,
+        other_device_data: DeviceData,
```
Comment (stefanceriu) [inline crates/matrix-sdk-crypto/src/verification/requests.rs:83]: @poljar We initially agreed to pass this `DeviceData` down into the `Transitioned` state but I couldn't identify were that would be useful 🤔

**Comment by stefanceriu** [comment]
Please double check the commit messages, I tried making them fit the new contributing guidelines but not sure I nailed it.

File: bindings/matrix-sdk-ffi/src/session_verification.rs [hunk 3]
```diff
@@ -60,80 +73,130 @@ pub struct SessionVerificationController {
...
+    }
+
+    /// Set this particular request as the currently active one and register for
+    /// events pertaining it.
+    /// * `sender_id` - The user requesting verification.
+    /// * `flow_id` - - The ID that uniquely identifies the verification flow.
+    pub async fn acknowledge_verification_request(
+        &self,
+        sender_id: String,
+        flow_id: String,
```
Comment (bmarty) [inline bindings/matrix-sdk-ffi/src/session_verification.rs:87]: Just a quick question regarding API usage: the `flow_id` is not enough here? We need to also provide the `sender_id`? (I believe that those data are coming from `SessionVerificationRequestDetails`).

Comment (stefanceriu) [reply bindings/matrix-sdk-ffi/src/session_verification.rs:87]: That's a good question, one I had myself. It's based on the underlying `OlmMachine::get_verification_request` which requires both, so there must be a good reason or it might be just because (maybe indexing by user ID so we can cancel existing requests for the same user https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk-crypto/src/verification/machine.rs#L168-L169)

Comment (bmarty) [reply bindings/matrix-sdk-ffi/src/session_verification.rs:87]: OK, thanks. That's fine, I was just wondering :)

File: bindings/matrix-sdk-ffi/src/session_verification.rs [hunk 4]
```diff
@@ -60,80 +73,130 @@ pub struct SessionVerificationController {
 
 #[matrix_sdk_ffi_macros::export]
 impl SessionVerificationController {
-    pub async fn is_verified(&self) -> Result<bool, ClientError> {
```
Comment (bmarty) [inline bindings/matrix-sdk-ffi/src/session_verification.rs:63]: Was this method removed by mistake @stefanceriu ? We are using it in EXA.

Comment (stefanceriu) [reply bindings/matrix-sdk-ffi/src/session_verification.rs:63]: Oh, it was intentional, you should be using `client.encryption().verificationState()` 🤔

Comment (bmarty) [reply bindings/matrix-sdk-ffi/src/session_verification.rs:63]: OK, that's what I have done, thanks for confirming!

File: crates/matrix-sdk-crypto/src/verification/requests.rs (hunk 2 above)
Comment (poljar) [reply crates/matrix-sdk-crypto/src/verification/requests.rs:83]: Well that's because, when we go from the `Requested` state into the `Ready` state you throw away the `DeviceData` and the `Ready` state again only remembers the device ID.

You should propagate the `DeviceData` to the `Ready` state here:

https://github.com/matrix-org/matrix-rust-sdk/blob/1d4b34f7c92d389d9ac5ed59377822603848c764/crates/matrix-sdk-crypto/src/verification/requests.rs#L915-L916

And then further to the `Transitioned` state, this would allow you to get rid of the second `get_device_call()` we have:

https://github.com/matrix-org/matrix-rust-sdk/blob/1d4b34f7c92d389d9ac5ed59377822603848c764/crates/matrix-sdk-crypto/src/verification/requests.rs#L1354-L1362

**Review by poljar — CHANGES_REQUESTED** [review]
Most of this look great, thanks for handling this. It is a bit unfinished though.

File: crates/matrix-sdk-crypto/src/verification/requests.rs (hunk 2 above)
Comment (stefanceriu) [reply crates/matrix-sdk-crypto/src/verification/requests.rs:83]: Nice, thank you for the very clear explanation, it should be good to go now! I've rebased the whole PR to help app developers but only the last 3 commits are new.

**Comment by richvdh** [comment]
Taking myself off the reviewer list here because it looks like @poljar already has context on it and will do a better job than me anyway

**Review by poljar — APPROVED** [review]
Very nice. Thanks for taking care of this.

**Comment by poljar** [comment]
Oh about the commits, some of them you got right some of them not.

`fix(crypto): ...` is correct, `crypto(verification)` is not. In the second case you should have used `fix(verification)` or something along those lines.

The format is documented here: https://www.conventionalcommits.org/en/v1.0.0/.
