### PR TITLE
Simplify the Room API

### LINKED ISSUE #2210: Sometimes the user can't join or leave rooms
While testing on Android, the QA team came across some issues when joining or leaving a room:

### Joining a room
Sometimes, when you try to accept a room invite, you can get:
> org.matrix.rustcomponents.sdk.ClientException$Generic: msg=Can't accept an invite for a room that isn't in invited state

This seems to happen randomly, but once this happens it seems like the result is cached and you won't be able to accept the invite until you restart the app.

### Leaving a room
Something similar happens when trying to leave a room, it sometimes will throw:
> org.matrix.rustcomponents.sdk.ClientException$Generic: msg=Can't leave a room that isn't in joined state

This seems easier to reproduce if the room was just joined, but I'm not sure if that's really related.

In both cases the state of the room in the Rust SDK doesn't seem to match what we have in the UI: if I could try to accept the invite is because I got it in the first place, and if I could leave the room is because I previously joined it.

### PR DESCRIPTION
**Pull request by jplatte**
- Remove the previous `Room`, `Joined`, `Invited` and `Left` types
- Merge all of the functionality from `Joined`, `Invited` and `Left` into `room::Common`
- Rename `room::Common` to just `Room` and made it accessible as `matrix_sdk::Room`

Fixes #2210.

### CODE REVIEW

**Comment by jmartinesp** [comment]
It works fine on Android, the issue seems to be completely fixed, thanks!

I'll leave the code review and approval to the Rust team thought 😅 .

File: crates/matrix-sdk/tests/integration/room/common.rs [hunk 1]
```diff
@@ -39,7 +39,7 @@ async fn user_presence() {
 
     let _response = client.sync_once(sync_settings).await.unwrap();
 
-    let room = client.get_joined_room(&test_json::DEFAULT_SYNC_ROOM_ID).unwrap();
+    let room = client.get_room(&test_json::DEFAULT_SYNC_ROOM_ID).unwrap();
```
Comment (bnjbvr) [inline crates/matrix-sdk/tests/integration/room/common.rs:42]: I know it's mega annoying to do this after the fact, but: in this entire file, would it make sense to assert that the room is in the join state?

File: crates/matrix-sdk/tests/integration/room/joined.rs [hunk 2]
```diff
@@ -42,7 +42,7 @@ async fn invite_user_by_id() {
     let _response = client.sync_once(sync_settings).await.unwrap();
 
     let user = user_id!("@example:localhost");
-    let room = client.get_joined_room(&test_json::DEFAULT_SYNC_ROOM_ID).unwrap();
+    let room = client.get_room(&test_json::DEFAULT_SYNC_ROOM_ID).unwrap();
```
Comment (bnjbvr) [inline crates/matrix-sdk/tests/integration/room/joined.rs:45]: and ditto in this file

File: testing/matrix-sdk-integration-testing/src/tests/redaction.rs [hunk 3]
```diff
@@ -34,12 +34,12 @@ async fn test_redacting_name() -> Result<()> {
...
     for _ in 0..=10 {
         sync_token = Some(sync_once(&tamatoa, sync_token).await?);
-        if tamatoa.get_joined_room(&room_id).is_some() {
+        if tamatoa.get_room(&room_id).is_some() {
             break;
         }
     }
 
-    let room = tamatoa.get_joined_room(&room_id).unwrap();
+    let room = tamatoa.get_room(&room_id).unwrap();
```
Comment (bnjbvr) [inline testing/matrix-sdk-integration-testing/src/tests/redaction.rs:42]: here too etc.

File: bindings/matrix-sdk-ffi/src/room.rs [hunk 4]
```diff
@@ -320,15 +313,6 @@ impl Room {
         fully_read_event_id: String,
         read_receipt_event_id: Option<String>,
     ) -> Result<(), ClientError> {
-        let room = match &self.inner {
-            SdkRoom::Joined(j) => j.clone(),
-            _ => {
-                return Err(
-                    anyhow!("Can't send read markers to room that isn't in joined state").into()
```
Comment (bnjbvr) [inline bindings/matrix-sdk-ffi/src/room.rs:327]: Can we have another check based on the room's state, for that? Any way to prevent confusing behavior, even at runtime, seems worth keeping IMO.

File: bindings/matrix-sdk-ffi/src/room.rs [hunk 5]
```diff
@@ -364,11 +348,6 @@ impl Room {
         in_reply_to_event_id: String,
         txn_id: Option<String>,
     ) -> Result<(), ClientError> {
-        let room = match &self.inner {
-            SdkRoom::Joined(j) => j.clone(),
-            _ => return Err(anyhow!("Can't send to a room that isn't in joined state").into()),
```
Comment (bnjbvr) [inline bindings/matrix-sdk-ffi/src/room.rs:369]: (and a few other times in this file)

File: crates/matrix-sdk-ui/src/timeline/mod.rs [hunk 6]
```diff
@@ -409,11 +403,11 @@ impl Timeline {
...
         let txn_id = TransactionId::new();
         let no_reason = RoomRedactionEventContent::default();
-        let room = self.joined_room();
 
-        let Ok(room) = room else {
-            return ReactionToggleResult::RedactFailure { event_id: event_id.to_owned() };
-        };
+        let room = self.room();
+        if room.state() != RoomState::Joined {
+            return ReactionToggleResult::AddFailure { txn_id };
```
Comment (bnjbvr) [inline crates/matrix-sdk-ui/src/timeline/mod.rs:409]: Fwiw, this was a `RedactFailure` before

**Review by bnjbvr — APPROVED** [review]
That's a nice PR, thanks for splitting it into meaningful commits. LGTM.

File: crates/matrix-sdk/tests/integration/room/common.rs (hunk 1 above)
Comment (jplatte) [reply crates/matrix-sdk/tests/integration/room/common.rs:42]: Is there much of a point? We have a bunch of tests where the state is asserted.

Comment (bnjbvr) [reply crates/matrix-sdk/tests/integration/room/common.rs:42]: Generally more testing, but I understand it's annoying, so feel free to ignore.

File: testing/matrix-sdk-integration-testing/src/tests/redaction.rs (hunk 3 above)
Comment (jplatte) [reply testing/matrix-sdk-integration-testing/src/tests/redaction.rs:42]: This is a full integration test that talks to a real server, the server will error further down when you're not actually joined.

File: bindings/matrix-sdk-ffi/src/room.rs (hunk 4 above)
Comment (jplatte) [reply bindings/matrix-sdk-ffi/src/room.rs:327]: If we did add that, it shouldn't be in the bindings. But I'd rather just not do it at all. By duplicating validations the server does anyways, we risk reporting an error when an action could actually have succeeded.

File: crates/matrix-sdk-ui/src/timeline/mod.rs (hunk 6 above)
Comment (jplatte) [reply crates/matrix-sdk-ui/src/timeline/mod.rs:409]: Oh, will change.

**Review by bnjbvr — APPROVED** [review]
