### PR TITLE
Respect room visibility while making automatic requests to fetch members

### LINKED ISSUE #244: Respect `Room History Visibility`
We currently send requests out that potentially can fail because of the [room history visibility ](https://matrix.org/docs/spec/client_server/r0.6.1#m-room-history-visibility). This is especially important for `Invited` rooms. We should make room members and messages requests only if the room history visibility allows us to do so. `invited` and `world_readable`  should allow us to view the room before the user actually joined so clients can display a preview.

### PR DESCRIPTION
**Pull request by SaurusXI**
Closes #244

### CODE REVIEW

File: matrix_sdk/src/room/common.rs [hunk 1]
```diff
@@ -169,13 +170,30 @@ impl Common {
     }
 
     async fn ensure_members(&self) -> Result<()> {
+        if !self.are_events_visible() {
+            return Err(
+                error::Error::Http(HttpError::NotClientRequest)
```
Comment (poljar) [inline matrix_sdk/src/room/common.rs:175]: The whole point of this endeavor is to not make HTTP requests that we know will fail, we should just return `Ok(())` here since we ensured that we did everything we can to synchronize the members.

File: matrix_sdk/src/room/common.rs [hunk 2]
```diff
@@ -169,13 +170,30 @@ impl Common {
...
             self.request_members().await?;
         }
 
         Ok(())
     }
 
+    fn are_events_visible(&self) -> bool {
+        if let RoomType::Invited = self.inner.room_type() {
+            return match self.inner.history_visibility() {
+                HistoryVisibility::WorldReadable | HistoryVisibility::Shared => true,
```
Comment (poljar) [inline matrix_sdk/src/room/common.rs:189]: Did you test that `Shared` allows us to fetch the members? It doesn't seem like it should based on the spec:

> shared - Previous events are always accessible to newly joined members. All events in the room are accessible, even those sent when the member was not a part of the room.

We are not a newly joined member, we're still only invited.

On the other hand `Invited` might behave that way:

> invited - Events are accessible to newly joined members from the point they were invited onwards. Events stop being accessible when the member’s state changes to something other than invite or join.

We are invited, and should have access to the state.

Am I missing something here?

**Review by poljar — CHANGES_REQUESTED** [review]
Looks mostly good but I think we need to tweak the logic a bit here.

File: matrix_sdk/src/room/common.rs (hunk 1 above)
Comment (SaurusXI) [reply matrix_sdk/src/room/common.rs:175]: Right, but I figured that we might want the information that the request was not made in the calling function. Throwing a recoverable error therefore seemed to be the way to go, since you can also just ignore the error if you don't need to handle it. 
Let me know if I should just return `Ok(())` instead.

File: matrix_sdk/src/room/common.rs (hunk 2 above)
Comment (SaurusXI) [reply matrix_sdk/src/room/common.rs:189]: Got it, I seem to have misunderstood the spec. Fixing.

File: matrix_sdk/src/room/common.rs (hunk 1 above)
Comment (poljar) [reply matrix_sdk/src/room/common.rs]: As you can see, that method is private. It's used to automatically synchronize the members, since that isn't possible unless we join or the history visibility changes there's no course of action the SDK can take to recover from this.

Comment (SaurusXI) [reply matrix_sdk/src/room/common.rs]: I see. How about using a custom enum type?
In that case, we might return `Ok(RequestMade)` and `Ok(RequestNotMade)` so information is propagated without throwing an `Err`.
Again just throwing ideas, let me know if you'd rather just return `Ok(())` here

Comment (poljar) [reply matrix_sdk/src/room/common.rs]: Not really necessary since it won't be propagated to the users, you can add a log line mentioning what's going on, that's something users could introspect.

Comment (SaurusXI) [reply matrix_sdk/src/room/common.rs]: Got it, changed it to return `Ok(())` instead

**Review by poljar — CHANGES_REQUESTED** [review]
Looks good, please just fix the clippy warning so CI can succeed.

**Review by poljar — APPROVED** [review]

**Comment by poljar** [comment]
Thanks, merged.
