### PR TITLE
test(timeline): In redecryption tests, sync after other user cross-signs

### LINKED ISSUE #4871: `test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_secure` is failing intermittently
cc @andybalaam as the test author :)

https://github.com/matrix-org/matrix-rust-sdk/actions/runs/14172826793/job/39700410337?pr=4747#step:10:2528

### PR DESCRIPTION
**Pull request by andybalaam**
Fixes #4871 (hopefully).

I can't reproduce the test flake in `test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_secure` locally, but I hope that by syncing after alice cross-signs, then bob has time for the information to arrive before fetching alice's identity.

### CODE REVIEW

File: testing/matrix-sdk-integration-testing/src/tests/timeline.rs [hunk 1]
```diff
@@ -890,9 +891,6 @@ async fn test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_
     }
 
     {
-        // Sanity: there is still just one message
-        assert_eq!(timeline_messages(&timeline).await.len(), 1);
```
Comment (andybalaam) [inline testing/matrix-sdk-integration-testing/src/tests/timeline.rs:894]: This is redundant since it's checked a few lines earlier.

**Review by bnjbvr — APPROVED** [review]
Thanks, let's try it out!
