### PR TITLE
timeline: reuse internal id when adding pending replied-to details to an item

### LINKED ISSUE #3379: FFI: Timeline::fetch_details_for_event updates the item's stable ID.
Calling `fetch_details_for_event` to get the reply details of an item <del>works fine when the request succeeds. But when it fails, the item is replaced with a new stable ID.</del> replaces the item with a new one, changing its stable ID. In EXI this results in unexpected timeline animations when it is the newest item:

https://github.com/matrix-org/matrix-rust-sdk/assets/6060466/f119dfe8-c5c7-4317-8733-572f27d1b060

### PR DESCRIPTION
**Pull request by bnjbvr**
Fixes #3379.

### CODE REVIEW

File: crates/matrix-sdk-ui/src/timeline/inner/mod.rs [hunk 1]
```diff
@@ -1290,18 +1297,20 @@ async fn fetch_replied_to_event(
...
+    // replied-to event to pending.
     trace!("Setting in-reply-to details to pending");
     let reply = message.with_in_reply_to(InReplyToDetails {
         event_id: in_reply_to.to_owned(),
         event: TimelineDetails::Pending,
     });
     let event_item = item.with_content(TimelineItemContent::Message(reply), None);
 
-    let new_timeline_item = state.meta.new_timeline_item(event_item);
+    let new_timeline_item = TimelineItem::new(event_item, internal_id);
```
Comment (bnjbvr) [inline crates/matrix-sdk-ui/src/timeline/inner/mod.rs:1313]: This line is the fix.

**Review by Hywan — APPROVED** [review]
LGTM!
