### PR TITLE
fix(sdk): Fix an infinite loop when loading pinned events from the storage

### LINKED ISSUE #6452: `PinnedEventCacheStateLockWriteGuard::reload_from_storage` can loop indefinitely
When looking at [a rageshake](https://github.com/element-hq/element-x-android-rageshakes/issues/11804) from Android, we saw the logs exploding, with thousands and thousands of instances of the same log line:

```
2026-04-15T08:46:28.622540Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 205.363µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.622782Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 207.682µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.622957Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 142.904µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.623138Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 147.42µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.623336Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 165.405µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.623575Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 204.956µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.623806Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 197.55µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.624046Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 193.969µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.624272Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 191.284µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.624501Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 196.858µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
2026-04-15T08:46:28.624725Z DEBUG matrix_sdk_sqlite::event_cache_store: Timer _method_ finished in 189.738µs | crates/matrix-sdk-sqlite/src/event_cache_store.rs:1151 | spans: pinned_event_listener_task{room_id=<room_id>:<homeserver>} > load_previous_chunk{linked_chunk_id=PinnedEvents("<room_id>:<homeserver>") before_chunk_identifier=ChunkIdentifier(0)}
```

That looks like this loop is not exited:

https://github.com/matrix-org/matrix-rust-sdk/blob/b5f5a9c90ef70e4777679a89b55d97b88fb1a66a/crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs#L131-L137

It could be caused by the `prev_chunk` referencing itself, however, the `insert_new_chunk_as_first` function called inside has lots of checks to prevent this from happening. Maybe one of those is wrong, or the new chunk is created in some way they're not checked correctly?

Thanks @Hywan for the early feedback about this issue.

### PR DESCRIPTION
**Pull request by Hywan**
This patch fixes a critical infinite loop when loading pinned events from the storage if and only if there is more than one chunk for the pinned events.

The previous implementation was broken in two ways:

1. if there was no previous chunk, then `prev` was set to `None`, but `previous` was never updated, so it was looping forever,
2. `load_previous_chunk` was called with the `last_chunk.previous` chunk identifier, which is incorrect: it must be called with the last chunk identifier, not the previous': otherwise it skips one chunk every time.

This patch adds a test to ensure everything works as expected.

---

- Fix #6452
- Follow up of https://github.com/matrix-org/matrix-rust-sdk/pull/6085

---

- [x] I've documented the public API Changes in the appropriate `CHANGELOG.md` files.
- [ ] This PR was made with the help of AI.

### CODE REVIEW

File: crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs [hunk 1]
```diff
@@ -543,3 +545,119 @@ impl PinnedEventCache {
         Ok(Some(loaded_events))
     }
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs]: Tests for this are included in `matrix-sdk/tests/integration/room/pinned_events.rs`, could you move them there instead, please?

File: crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs [hunk 2]
```diff
@@ -124,15 +124,17 @@ impl<'a> PinnedEventCacheStateLockWriteGuard<'a> {
...
-        let mut previous = last_chunk.previous;
-        self.state.chunk.replace_with(Some(last_chunk), chunk_id_gen)?;
-
-        // Reload the entire chunk.
-        while let Some(previous_chunk_id) = previous {
-            let prev = self.store.load_previous_chunk(linked_chunk_id, previous_chunk_id).await?;
-            if let Some(prev_chunk) = prev {
-                previous = prev_chunk.previous;
-                self.state.chunk.insert_new_chunk_as_first(prev_chunk)?;
+        {
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs:127]: I don't think the extra scope buys us anything?

File: crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs [hunk 3]
```diff
@@ -124,15 +124,17 @@ impl<'a> PinnedEventCacheStateLockWriteGuard<'a> {
...
+            let mut current_chunk_identifier = last_chunk.identifier;
+            self.state.chunk.replace_with(Some(last_chunk), chunk_id_gen)?;
+
+            // Reload the entire chunk.
+            while let Some(previous_chunk) =
+                self.store.load_previous_chunk(linked_chunk_id, current_chunk_identifier).await?
+            {
+                // A previous chunk exists. Insert it in the `LinkedChunk`.
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs]: This comment re-says in words what the one line of code at L137 does, is it really worth it?

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Big duh on this one, thanks for fixing! It's surprising that a room gets more than 2 chunks of pinned events, but I guess this could happen for a room that has more than 128 pinned events 🤔

**Comment by jmartinesp** [comment]
> It's surprising that a room gets more than 2 chunks of pinned events, but I guess this could happen for a room that has more than 128 pinned events 🤔

[According to the reporter](https://github.com/element-hq/element-x-android/issues/6534#issuecomment-4250891833), this room had 6 pinned events 🫤 .

File: crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs (hunk 2 above)
Comment (Hywan) [reply crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs:127]: `current_chunk_identifier` is not accessible outside this scope. It also scopes the full load of the LinkedChunk, which is not a bad thing.

File: crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs (hunk 1 above)
Comment (Hywan) [reply crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs]: Done.

File: crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs (hunk 3 above)
Comment (Hywan) [reply crates/matrix-sdk/src/event_cache/caches/pinned_events/mod.rs]: Removed.

**Comment by Hywan** [comment]
I don't understand neither how a gap was inserted here, but either we assume only one chunk can exist, and the loop must be removed, or we should load all the chunks correctly. I took the safe approach by fixing this critical bug first.

**Review by bnjbvr — APPROVED** [review]
Thanks!

**Review by bxdxnn — APPROVED** [review]
Works fine, sadly I can't tell if it fixes my problem or not as I had a clean storage on the debug build.
