### PR TITLE
fix(integration-tests): Fixes #4871 (hopefully). Repeatedly sync in a test after other user cross-signs

### LINKED ISSUE #4871: `test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_secure` is failing intermittently
cc @andybalaam as the test author :)

https://github.com/matrix-org/matrix-rust-sdk/actions/runs/14172826793/job/39700410337?pr=4747#step:10:2528

### PR DESCRIPTION
**Pull request by andybalaam**
Fixes #4871 (hopefully). In `test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_secure`, we think we might need to sync twice to persuade the client or server to notice the update to alice's idenitity.

### CODE REVIEW

File: testing/matrix-sdk-integration-testing/src/tests/timeline.rs [hunk 1]
```diff
@@ -873,6 +873,13 @@ async fn test_new_users_first_messages_dont_warn_about_insecure_device_if_it_is_
     // But when alice becomes cross-signed and bob finds out about it
     cross_sign(&alice).await;
     bob.sync_once(SyncSettings::new()).await.expect("should not fail to sync");
+
+    // Sync again to make sure the server has notified us about the update to
+    // alice's device info.
+    bob.sync_once(SyncSettings::new().timeout(Duration::from_millis(2000)))
```
Comment (bnjbvr) [inline testing/matrix-sdk-integration-testing/src/tests/timeline.rs:879]: Ah nice, I thought you'd be using `tokio::time::timeout` but using the timeout from `SyncSettings` is even better if it achieves the same effect :+1:

**Review by bnjbvr — APPROVED** [review]
Let's try it out! :crossed_fingers:

File: testing/matrix-sdk-integration-testing/src/tests/timeline.rs (hunk 1 above)
Comment (andybalaam) [reply testing/matrix-sdk-integration-testing/src/tests/timeline.rs:879]: It seems to work...
