### PR TITLE
fix(ui): Do not filter out own receipts in load_read_receipts_for_event

### LINKED ISSUE #4517: Timeline has the wrong latest read receipt sometimes
Calling `Timeline::latest_user_read_receipt` or `Timeline::latest_user_read_receipt_timeline_event_id` sometimes returns the latest event sent by the user (so the latest implicit read receipt) instead of the latest explicit read receipt, although the latest explicit read receipt is more recent in history than the implicit read receipt.

It seems to prioritize somehow implicit read receipts over explicit read receipts.

Here is a test that reproduces the error:

```diff
diff --git a/crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs b/crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
index 99ef23a08..0086b13e4 100644
--- a/crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
+++ b/crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs
@@ -612,3 +612,94 @@ async fn test_clear_read_receipts() {
     assert_eq!(event_b.read_receipts().len(), 1);
     assert!(event_b.read_receipts().get(*BOB).is_some());
 }
+
+#[async_test]
+async fn test_implicit_read_receipt_before_explicit_read_receipt() {
+    // Test a timeline in this order:
+    // 1. $alice_event: sent by alice, has no explicit read receipts.
+    // 2. $bob_event: sent by bob, has no explicit read receipts.
+    // 3. $carol_event: sent by carol, has the explicit read receipts of all users.
+    let room_id = room_id!("!room:localhost");
+    let alice_event_id = owned_event_id!("$alice_event");
+    let bob_event_id = owned_event_id!("$bob_event");
+    let carol_event_id = owned_event_id!("$carol_event");
+
+    // Add initial private receipt on the main thread.
+    let mut initial_user_receipts = ReadReceiptMap::new();
+    let unthreaded_read_receipts = initial_user_receipts
+        .entry(ReceiptType::Read)
+        .or_default()
+        .entry(ReceiptThread::Unthreaded)
+        .or_default();
+    unthreaded_read_receipts.insert(
+        ALICE.to_owned(),
+        (carol_event_id.clone(), Receipt::new(ruma::MilliSecondsSinceUnixEpoch(uint!(10)))),
+    );
+    unthreaded_read_receipts.insert(
+        BOB.to_owned(),
+        (carol_event_id.clone(), Receipt::new(ruma::MilliSecondsSinceUnixEpoch(uint!(5)))),
+    );
+    unthreaded_read_receipts.insert(
+        CAROL.to_owned(),
+        (carol_event_id.clone(), Receipt::new(ruma::MilliSecondsSinceUnixEpoch(uint!(1)))),
+    );
+
+    let timeline = TestTimeline::with_room_data_provider(
+        TestRoomDataProvider::default().with_initial_user_receipts(initial_user_receipts),
+    )
+    .with_settings(TimelineSettings { track_read_receipts: true, ..Default::default() });
+
+    // Check that the receipts are at the correct place.
+    let (receipt_event_id, _) = timeline.controller.latest_user_read_receipt(*ALICE).await.unwrap();
+    assert_eq!(receipt_event_id, carol_event_id);
+    let (receipt_event_id, _) = timeline.controller.latest_user_read_receipt(*BOB).await.unwrap();
+    assert_eq!(receipt_event_id, carol_event_id);
+    let (receipt_event_id, _) = timeline.controller.latest_user_read_receipt(*CAROL).await.unwrap();
+    assert_eq!(receipt_event_id, carol_event_id);
+
+    // Add the events.
+    let carol_event_content = RoomMessageEventContent::text_plain("I am Carol!");
+    timeline
+        .handle_back_paginated_event(
+            timeline
+                .factory
+                .event(carol_event_content)
+                .sender(*CAROL)
+                .room(room_id)
+                .event_id(&carol_event_id)
+                .into_raw_timeline(),
+        )
+        .await;
+    let bob_event_content = RoomMessageEventContent::text_plain("I am Bob!");
+    timeline
+        .handle_back_paginated_event(
+            timeline
+                .factory
+                .event(bob_event_content)
+                .sender(*BOB)
+                .room(room_id)
+                .event_id(&bob_event_id)
+                .into_raw_timeline(),
+        )
+        .await;
+    let alice_event_content = RoomMessageEventContent::text_plain("I am Alice!");
+    timeline
+        .handle_back_paginated_event(
+            timeline
+                .factory
+                .event(alice_event_content)
+                .sender(*ALICE)
+                .room(room_id)
+                .event_id(&alice_event_id)
+                .into_raw_timeline(),
+        )
+        .await;
+
+    // The receipts shouldn't have moved.
+    let (receipt_event_id, _) = timeline.controller.latest_user_read_receipt(*ALICE).await.unwrap();
+    assert_eq!(receipt_event_id, carol_event_id); // This fails, it is now equal to `alice_event_id`.
+    let (receipt_event_id, _) = timeline.controller.latest_user_read_receipt(*BOB).await.unwrap();
+    assert_eq!(receipt_event_id, carol_event_id); // This fails, it is now equal to `bob_event_id`.
+    let (receipt_event_id, _) = timeline.controller.latest_user_read_receipt(*CAROL).await.unwrap();
+    assert_eq!(receipt_event_id, carol_event_id);
+}
```

### PR DESCRIPTION
**Pull request by zecakeh**
Fixes #4517.

It turns out that the bugs found in that test were due to 2 causes:

- First commit: `TestRoomDataProvider` didn't use `initial_user_receipts` but returned hardcoded values.
- Second commit: Our own read receipts were ignored in `TimelineStateTransaction::load_read_receipts_for_event`, although we need to process all read receipts via `ReadReceipts::maybe_update_read_receipt` because it knows how to filter out our own read receipts were needed.

### CODE REVIEW

File: crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs [hunk 1]
```diff
@@ -647,3 +647,94 @@ async fn test_clear_read_receipts() {
...
+    let (receipt_event_id, _) = timeline.controller.latest_user_read_receipt(*CAROL).await.unwrap();
+    assert_eq!(receipt_event_id, carol_event_id);
+
+    // Add the events.
+    let carol_event_content = RoomMessageEventContent::text_plain("I am Carol!");
+    timeline
+        .handle_back_paginated_event(
+            timeline
+                .factory
+                .event(carol_event_content)
```
Comment (bnjbvr) [inline crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs:701]: can call `.text_msg("I am Carol!")` instead of creating the `RoomMessageEventContent` manually.

File: crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs [hunk 2]
```diff
@@ -647,3 +647,94 @@ async fn test_clear_read_receipts() {
...
+                .event_id(&carol_event_id)
+                .into_raw_timeline(),
+        )
+        .await;
+    let bob_event_content = RoomMessageEventContent::text_plain("I am Bob!");
+    timeline
+        .handle_back_paginated_event(
+            timeline
+                .factory
+                .event(bob_event_content)
```
Comment (bnjbvr) [inline crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs:713]: ditto here

File: crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs [hunk 3]
```diff
@@ -647,3 +647,94 @@ async fn test_clear_read_receipts() {
...
+                .event_id(&bob_event_id)
+                .into_raw_timeline(),
+        )
+        .await;
+    let alice_event_content = RoomMessageEventContent::text_plain("I am Alice!");
+    timeline
+        .handle_back_paginated_event(
+            timeline
+                .factory
+                .event(alice_event_content)
```
Comment (bnjbvr) [inline crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs:725]: and ditto here

**Review by bnjbvr — APPROVED** [review]
Thanks for fixing <3

File: crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs (hunk 1 above)
Comment (zecakeh) [reply crates/matrix-sdk-ui/src/timeline/tests/read_receipts.rs]: Done

**Review by bnjbvr — APPROVED** [review]
