### PR TITLE
Small improvements to `App` API

### LINKED ISSUE #2247: `SlidingSync.is_syncing` is not reliable
We had an error in Element X Android where we left a test line calling `roomListService.sync()` an extra time and we started seeing several issues:

- Very long times to load the room list.
- The timeline updates unreliably.
- Invites don't disappear from the invite list when they are accepted.

It seemed weird, because we had checks to prevent several sync loops from being created:

```kotlin
fun startSync() = runCatching {
    if (!roomListService.isSyncing()) {
        roomListService.sync()
    }
}
```

But it turns out this `isSyncing()` call is not reliable: it's just [a shorthand](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/room_list.rs#L130) for checking if the internal state of the room list is either running or being set up.

However, given how this state is updated in an asynchronous way here: https://github.com/matrix-org/matrix-rust-sdk/blob/89aa2916c7b6137a27da50f8fc8c4462575f8ca5/crates/matrix-sdk-ui/src/room_list_service/mod.rs#L209

It can happen that it returns false for some time, while the room list is actually being set up, and then a new sync loop is created. That's exactly what we saw in our logs:

```
2023-07-10 11:24:52.241  7115-7115  RustSyncService           io....nt.android.x.debug  D  Start sync - 1
2023-07-10 11:24:52.263  7115-7115  RustSyncService           io....nt.android.x.debug  D  Start sync - 2
2023-07-10 11:24:54.126  7115-7115  RustSyncService           io....nt.android.x.debug  D  Start sync - 3
```

Also, does it make sense that we can actually start several sync loops? Is there some use case for that, or should that fail at the SDK level?

### PR DESCRIPTION
**Pull request by bnjbvr**
- get rid of `RoomListService::is_syncing`; on the one hand it's slightly confusing in itself (because it considers that it's not syncing while in init state, which is eyebrow-raising worthy at the bare minimum), but now it's also incorrect to look at this state if used with the `App` API. The encryption sync may be stopped and cause a stop of the `App` stream, but the room list service's SS would only be interrupted slightly later, causing some confusing race conditions. Fixes #2247.
- don't automatically start the `App` upon creation. After feedback from both @ganfra and @stefanceriu this is more confusing than helpful.
- add `App::current_state` to provide the current application's state, in addition to the state subscriber. Both are useful at different times, and having both makes it so that the client doesn't need to store the state anymore, causing fewer opportunities for state mismanagement.

### CODE REVIEW

**Review by stefanceriu — APPROVED** [review]
🚀

File: bindings/matrix-sdk-ffi/src/app.rs [hunk 1]
```diff
@@ -70,6 +72,10 @@ impl App {
         })))
     }
 
+    pub fn current_state(&self) -> AppState {
+        self.inner.observe_state().get().into()
+    }
```
Comment (jplatte) [inline bindings/matrix-sdk-ffi/src/app.rs:77]: Maybe instead of an extra method we should send the current state immediately when subscribing? Like done [here](https://github.com/matrix-org/matrix-rust-sdk/pull/2245/files).

File: crates/matrix-sdk-ui/src/app/mod.rs [hunk 2]
```diff
@@ -74,22 +75,35 @@ impl App {
     /// Observe the current state of the application.
     ///
     /// See also [`AppState`].
-    pub fn observe_state(&self) -> impl Stream<Item = AppState> {
+    pub fn observe_state(&self) -> Subscriber<AppState> {
```
Comment (jplatte) [inline crates/matrix-sdk-ui/src/app/mod.rs:78]: Not exactly related to this PR, but I don't think we use the `observe_` prefix elsewhere, might make sense to remove?

**Review by jplatte — APPROVED** [review]

File: bindings/matrix-sdk-ffi/src/app.rs (hunk 1 above)
Comment (bnjbvr) [reply bindings/matrix-sdk-ffi/src/app.rs:77]: Yep, I expect that they be used at different times, so I'll keep it like this :+1:

File: crates/matrix-sdk-ui/src/app/mod.rs (hunk 2 above)
Comment (bnjbvr) [reply crates/matrix-sdk-ui/src/app/mod.rs]: that's right; I've removed it.
