### PR TITLE
send queue: allow unwedging and retry after recipient trust changes

### LINKED ISSUE #3837: [Task] Restore the method to retry sending of failed messages
Part of the crypto work from https://github.com/element-hq/element-meta/issues/2488

Whilst most send failures can be resolved automatically (e.g. network failures, invalid access token etc) or are deemed unrecoverable (e.g. invalid data, too large etc) there are some instances where a message can fail to send but may work later:

- The other user was verified but has become unverified (will succeed when they're verified again).
- The other user is verified but has an unverified device (will succeed when the device has been verified).

Having a method to retry sending of an item will be useful for this.

### LINKED ISSUE #3838: [Task] Add a method to resolve send failures due to unverified devices and retry sending.
Part of https://github.com/element-hq/element-meta/issues/2501 and likely requires https://github.com/matrix-org/matrix-rust-sdk/issues/3837

Once the error is surface from https://github.com/matrix-org/matrix-rust-sdk/issues/3792 we need a way to allow a user to resolve the error and retry sending. This can be done in the following way:

> For unverified device: In order to send anyhow, you have to blacklist or whitelist the device using `Device::set_local_trust` (you have all the problematic devices listed in the error) then just resend⁦

### LINKED ISSUE #3839: [Task] Add a method to resolve send failures due to an identity change and retry sending.
Part of https://github.com/element-hq/element-meta/issues/2500 and likely requires https://github.com/matrix-org/matrix-rust-sdk/issues/3837

Once the error is surface from https://github.com/matrix-org/matrix-rust-sdk/issues/3793 we need a way to allow a user to resolve the error and retry sending. This can be done in the following way:

> For "verification violation" there is a new `UserIdentity::withdraw_verification` that you can call, then retry sending. (you can also blacklist if you prefer via `Device::set_local_trust`)
> ⁦And same the error gaves you all the problematic `user_id`, so you can just iterate, withdraw_verification then resend

### PR DESCRIPTION
**Pull request by stefanceriu**
* add a generic mechanism for unwedging and resending requests based on their transaction identifier
* expose methods for manually withdrawing certain users' verification or trusting their devices and resending failed messages

This will be used in conjunction with the send errors introduced in https://github.com/matrix-org/matrix-rust-sdk/pull/3866 to allow the user to force resend failed messages after manually resolving trust issues.

Fixes #3839, fixes #3838, fixes #3837.

### CODE REVIEW

File: crates/matrix-sdk/src/room/mod.rs [hunk 1]
```diff
@@ -2957,6 +2962,54 @@ impl Room {
...
+        &self,
+        devices: HashMap<OwnedUserId, Vec<OwnedDeviceId>>,
+        transaction_id: &TransactionId,
+    ) -> Result<()> {
+        let encryption = self.client().encryption();
+
+        for user_id in devices.keys() {
+            for device_id in &devices[user_id] {
+                if let Some(device) = encryption.get_device(user_id, device_id).await? {
+                    device.set_local_trust(LocalTrust::Verified).await?;
```
Comment (pixlwave) [inline crates/matrix-sdk/src/room/mod.rs:3004]: Just tested this and turns out we need to set it to `LocalTrust::Ignored` here.

File: crates/matrix-sdk/src/room/mod.rs [hunk 2]
```diff
@@ -2957,6 +2962,54 @@ impl Room {
...
+
+        Ok(())
+    }
+
+    /// Set the local trust for the given devices to `LocalTrust::Verified`
+    /// and resend messages that failed to send because said devices are
+    /// unverified (in response to
+    /// `SessionRecipientCollectionError::VerifiedUserHasUnsignedDevice`).
+    #[cfg(feature = "e2e-encryption")]
+    pub async fn trust_devices_and_resend(
```
Comment (pixlwave) [inline crates/matrix-sdk/src/room/mod.rs:2994]: I guess this should probably then become something like `ignore_device_trust_and_resend`

File: crates/matrix-sdk/src/send_queue.rs [hunk 3]
```diff
@@ -556,6 +556,20 @@ impl RoomSendQueue {
...
+    /// Unwedge a local echo identified by its transaction identifier and try to
+    /// resend it.
+    pub async fn unwedge(&self, transaction_id: &TransactionId) -> Result<(), RoomSendQueueError> {
+        self.inner
+            .queue
+            .mark_as_unwedged(transaction_id)
+            .await
+            .map_err(RoomSendQueueError::StorageError)?;
+
+        self.inner.notifier.notify_one();
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/send_queue.rs:569]: Can you add a comment here similar to others doing the same thing, explaining why we're notifying?

File: crates/matrix-sdk/src/send_queue.rs [hunk 4]
```diff
@@ -673,6 +687,19 @@ impl QueueStorage {
             .await?)
     }
 
+    /// Marks an event identified with the given transaction id as being now
+    /// unwedged and adds it back to the queue
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/send_queue.rs:696]: uber-nit: final dot at the end for consistency with the rest of this file :)

File: crates/matrix-sdk/tests/integration/send_queue.rs [hunk 5]
```diff
@@ -1398,6 +1398,94 @@ async fn test_unrecoverable_errors() {
...
+    // The room updates will report the error for the first message as unrecoverable
+    // too.
+    assert_update!(watch => error { recoverable=false, txn=txn1 });
+
+    // No queue is being disabled, because the error was unrecoverable.
+    assert!(room.send_queue().is_enabled());
+    assert!(client.send_queue().is_enabled());
+
+    // Unwedge the previously failed message and try sending it again
+    let _ = q.unwedge(&txn1).await;
```
Comment (bnjbvr) [inline crates/matrix-sdk/tests/integration/send_queue.rs:1493]: instead of ignoring the result, please `.unwrap()` at the end to make sure it's an `Ok()` result.

File: crates/matrix-sdk/src/room/mod.rs [hunk 6]
```diff
@@ -2957,6 +2962,54 @@ impl Room {
...
+    ) -> Result<()> {
+        let encryption = self.client().encryption();
+
+        for user_id in user_ids {
+            if let Some(user_identity) = encryption.get_user_identity(&user_id).await? {
+                user_identity.withdraw_verification().await?;
+            }
+        }
+
+        self.send_queue().unwedge(transaction_id).await?;
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/room/mod.rs:2984]: The API here is weird, because it's undocumented anywhere what the transaction_id is for, and that's it's one managed by the send queue. I'd remove this line from this function and the other, and instead have the callers at the FFI layer call the `unwedge` function and document the transaction id properties.

File: crates/matrix-sdk/src/room/mod.rs [hunk 7]
```diff
@@ -2957,6 +2962,54 @@ impl Room {
...
+
+        for user_id in devices.keys() {
+            for device_id in &devices[user_id] {
+                if let Some(device) = encryption.get_device(user_id, device_id).await? {
+                    device.set_local_trust(LocalTrust::Verified).await?;
+                }
+            }
+        }
+
+        self.send_queue().unwedge(transaction_id).await?;
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/room/mod.rs:3009]: here too

File: crates/matrix-sdk/src/room/mod.rs [hunk 8]
```diff
@@ -2957,6 +2962,54 @@ impl Room {
             .await?;
         Ok(())
     }
+
+    /// Remove verification requirements for the given users and
+    /// resend messages that failed to send because their identities were no
+    /// longer verified (in response to
+    /// `SessionRecipientCollectionError::VerifiedUserChangedIdentity`)
+    #[cfg(feature = "e2e-encryption")]
+    pub async fn withdraw_verification_and_resend(
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/room/mod.rs:2971]: Should these two methods live in the `Encryption` API object instead? They don't make any usage of the room, except for getting the send queue, which I argued below isn't the right place to do it.

Comment (bnjbvr) [reply crates/matrix-sdk/src/room/mod.rs:2971]: Also these two functions would need individual tests please 😁

File: crates/matrix-sdk/src/error.rs [hunk 9]
```diff
@@ -379,6 +381,10 @@ pub enum Error {
     /// Backups are not enabled
     #[error("backups are not enabled")]
     BackupNotEnabled,
+
+    /// An error coming from the send queue subsystem.
+    #[error(transparent)]
+    SendQueueError(#[from] RoomSendQueueError),
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/error.rs:387]: With my suggestion below, you can likely remove this…

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Good job on the send queue! I disagree with the other methods' API shape a little though, so let's rethink it through.

File: crates/matrix-sdk/src/room/mod.rs (hunk 6 above)
Comment (stefanceriu) [reply crates/matrix-sdk/src/room/mod.rs:2984]: Just to make sure I get it straight: 
1) We would move `withdraw_verification` and `trust_devices` to Encryption
2) We would expose unwedge by txnId on the Room level
3) The final client would first trust via Client and then resend via Room

Does that sounds about right?

File: crates/matrix-sdk/src/room/mod.rs (hunk 8 above)
Comment (stefanceriu) [reply crates/matrix-sdk/src/room/mod.rs:2971]: > these two functions would need individual tests

I reckon that if we split them up from the resending they would just proxy to the crypto crate where they're already tested.

File: crates/matrix-sdk/src/room/mod.rs (hunk 6 above)
Comment (bnjbvr) [reply crates/matrix-sdk/src/room/mod.rs:2984]: > We would expose unwedge by txnId on the Room level

Do we need to, or can the caller themselves do `room.send_queue().unwedge(transaction_id)`? The idea here is that we should make it clear why it's ok to pass a transcation id to the send queue; it's because it's originating from the send queue too, and this information is super hidden at the moment, with the current API shape.

To be honest, I'm thinking all of this, the loop included above, could happen at the FFI layer, if it's just calling into other existing APIs without adding other value.

Consider the semantics carefully though: if any of the verification withdrawing fails, is it ok that 1. others have been successful, 2. we don't unwedge in that case?

Comment (stefanceriu) [reply crates/matrix-sdk/src/room/mod.rs:2984]: > Do we need to, or can the caller themselves do room.send_queue().unwedge(transaction_id)

Oh I see, I'm thinking of it from the FFI layer and you're talking SDK. Yeah that would be totally okay

> all of this, the loop included above, could happen at the FFI layer

Right yeah, I agree!

> Consider the semantics carefully though

I have, I think that bit's fine. Retrying to send it while some of the devices/users from the original failure haven't been resolved will result in the same error.

File: bindings/matrix-sdk-ffi/src/room.rs [hunk 10]
```diff
@@ -737,6 +738,68 @@ impl Room {
         self.inner.send_queue().send(replacement_event).await?;
         Ok(())
     }
+
+    /// Remove verification requirements for the given users and
+    /// resend messages that failed to send because their identities were no
+    /// longer verified (in response to
+    /// `SessionRecipientCollectionError::VerifiedUserChangedIdentity`)
```
Comment (bnjbvr) [inline bindings/matrix-sdk-ffi/src/room.rs:745]: please document that the `transaction_id` is one coming from the send queue

File: bindings/matrix-sdk-ffi/src/room.rs [hunk 11]
```diff
@@ -737,6 +738,68 @@ impl Room {
...
+    pub async fn withdraw_verification_and_resend(
+        &self,
+        user_ids: Vec<String>,
+        transaction_id: String,
+    ) -> Result<(), ClientError> {
+        let transaction_id: OwnedTransactionId = transaction_id.into();
+
+        let parsing_result: Result<Vec<OwnedUserId>, _> =
+            user_ids.iter().map(UserId::parse).collect();
```
Comment (bnjbvr) [inline bindings/matrix-sdk-ffi/src/room.rs:754]: One of these should work:

```suggestion
        let user_ids: Vec<OwnedUserId> = user_ids.iter().map(UserId::parse).collect()?;
```


```suggestion
        let user_ids: Vec<OwnedUserId> = user_ids.iter().map(UserId::parse).collect::<Result<_, _>>()?;
```

File: bindings/matrix-sdk-ffi/src/room.rs [hunk 12]
```diff
@@ -737,6 +738,68 @@ impl Room {
...
+            Err(error) => return Err(ClientError::new(error)),
+        };
+
+        Ok(())
+    }
+
+    /// Set the local trust for the given devices to `LocalTrust::Ignored`
+    /// and resend messages that failed to send because said devices are
+    /// unverified (in response to
+    /// `SessionRecipientCollectionError::VerifiedUserHasUnsignedDevice`).
```
Comment (bnjbvr) [inline bindings/matrix-sdk-ffi/src/room.rs:777]: Same comment about the transaction id here.

File: crates/matrix-sdk/src/error.rs (hunk 9 above)
Comment (bnjbvr) [reply crates/matrix-sdk/src/error.rs:387]: Can this not be removed, now?

File: crates/matrix-sdk/src/send_queue.rs [hunk 13]
```diff
@@ -673,6 +693,19 @@ impl QueueStorage {
...
+    /// Marks an event identified with the given transaction id as being now
+    /// unwedged and adds it back to the queue.
+    async fn mark_as_unwedged(
+        &self,
+        transaction_id: &TransactionId,
+    ) -> Result<(), RoomSendQueueStorageError> {
+        Ok(self
+            .client()?
+            .store()
+            .update_send_queue_event_status(&self.room_id, transaction_id, false)
```
Comment (bnjbvr) [inline crates/matrix-sdk/src/send_queue.rs:705]: Hmm I'm wondering if this function should return a boolean, to indicate if the underlying item with such a transaction id was found, otherwise this might give a false sense that something happened, while it's not the case… (if one passes an invalid transaction id, for instance)

We don't have to do it in this PR, though.

**Review by bnjbvr — CHANGES_REQUESTED** [review]
Getting closer!

File: crates/matrix-sdk/src/error.rs (hunk 9 above)
Comment (stefanceriu) [reply crates/matrix-sdk/src/error.rs:387]: Sorry, I completely missed this in the previous pass, was literally working on removing it 👍

File: bindings/matrix-sdk-ffi/src/room.rs (hunk 11 above)
Comment (stefanceriu) [reply bindings/matrix-sdk-ffi/src/room.rs:754]: Oh sweet, the second one does! So I can specialise collect to avoid inference issues, that's the bit I was missing when I first tried to write it that way. Really cool 👍

File: crates/matrix-sdk/src/send_queue.rs (hunk 13 above)
Comment (stefanceriu) [reply crates/matrix-sdk/src/send_queue.rs:705]: Oh yeah, that would make sense but why not return an error directly?

File: bindings/matrix-sdk-ffi/src/error.rs [hunk 14]
```diff
@@ -134,14 +134,14 @@ impl From<EventCacheError> for ClientError {
...
+    fn from(e: EditError) -> Self {
         Self::new(e)
     }
 }
 
-impl From<EditError> for ClientError {
-    fn from(e: EditError) -> Self {
+impl From<RoomSendQueueError> for ClientError {
+    fn from(e: RoomSendQueueError) -> Self {
         Self::new(e)
```
Comment (bnjbvr) [inline bindings/matrix-sdk-ffi/src/error.rs:145]: :eyes: something fun is going on here…

File: crates/matrix-sdk/src/send_queue.rs (hunk 13 above)
Comment (bnjbvr) [reply crates/matrix-sdk/src/send_queue.rs:705]: It's a philosophical question: is it an error to misuse the API with a transaction id that's not handled by the send queue, or should we signal it nicely so that the user can try something else with that transaction id?

**Review by bnjbvr — APPROVED** [review]
lgtm, thanks

File: bindings/matrix-sdk-ffi/src/error.rs (hunk 14 above)
Comment (stefanceriu) [reply bindings/matrix-sdk-ffi/src/error.rs:145]: Yeah, I don't understand what its problem is.

File: crates/matrix-sdk/src/send_queue.rs (hunk 13 above)
Comment (stefanceriu) [reply crates/matrix-sdk/src/send_queue.rs:705]: I would passing in an invalid/unknown transaction id should be a developer error, api missuse. Giving back a boolean might be unclear to what actually went wrong.
