### PR TITLE
fix(base): Detect left room in `SlidingSyncResponse`

### LINKED ISSUE #2300: Leaving a DM returns the room that was left when calling get_dm_room
This is all through the FFI. Steps to reproduce:

- Create a DM room with someone (EX code [here](https://github.com/vector-im/element-x-ios/blob/6b030172e59d8fb3307018e1a7f18c1f985515a2/ElementX/Sources/Services/Client/ClientProxy.swift#L160-L161)).
- Send some messages (probably not relevant).
- They join the room (probably not relevant).
- Leave the room (by calling `room.leave()`).
- Call `client.get_dm_room(someone)` for the same person.

The room returned is the room that was left:

https://github.com/matrix-org/matrix-rust-sdk/assets/6060466/8d4569a7-89b7-4411-81dd-0fd2cc2108fb

### PR DESCRIPTION
**Pull request by Hywan**
OK so here is the story.

In `matrix_sdk_base`, we extend the `BaseClient` to add `SlidingSync` feature. Among many things, we map a `SlidingSyncResponse` into a `SyncResponse`, and we update all the inner types like `Room` etc.

In #2300, @poljar [has noticed that we have a `FIXME` in our code](https://github.com/matrix-org/matrix-rust-sdk/issues/2300#issuecomment-1661836252) saying that any room that isn't in an `Invite` state is considered `Join`. It misses one case: `Left`. Technically, what the code does is: either the room is in `Invite` state, and we do our stuff, or we create a new room in a `Join` state, and update the room's state based on the `required_state` provided in the `SlidingSyncResponse`.

From here, I've started to investigate with @pixlwave (thanks!). We have noticed that the server send the same event twice (tracked https://github.com/matrix-org/sliding-sync/issues/250). But we have also noticed that the state event containing the `"membership": "leave"` value was not sent as part of the `required_state` events as it happens most of the time, but this time as part of the `timeline` events!

This patch then updates the code to look for state events in the `required_state` as before, but _also_ in `timeline`.

I recommend to review this PR commit-by-commit. I tried to make commit standalone with useful descriptions as much as possible.

---

* Fixes #2300
* Partly address https://github.com/matrix-org/matrix-rust-sdk/issues/2078, another patch might be needed to fix all issues raised there.

### CODE REVIEW

**Comment by pixlwave** [comment]
I can confirm this fixes the issue on iOS.

File: crates/matrix-sdk-base/src/sliding_sync.rs [hunk 1]
```diff
@@ -402,6 +405,35 @@ impl BaseClient {
...
         }
     }
+
+    pub(crate) fn deserialize_state_events_from_timeline(
+        raw_events: &[Raw<AnySyncTimelineEvent>],
+    ) -> Vec<(Raw<AnySyncStateEvent>, AnySyncStateEvent)> {
+        raw_events
+            .iter()
+            .filter_map(|raw_event| {
+                if raw_event.get_field::<serde::de::IgnoredAny>("state_key").is_ok() {
```
Comment (jplatte) [inline crates/matrix-sdk-base/src/sliding_sync.rs:435]: `get_field` returns `Result<Option<T>, serde_json:Error>`. It would return `Err` if the field exists but deserialization as `IgnoredAny` fails (which is impossible). You have to check whether the inner `Option` is `Some`, e.g. using `.transpose().is_some()`.

File: crates/matrix-sdk-base/src/sliding_sync.rs [hunk 2]
```diff
@@ -402,6 +405,35 @@ impl BaseClient {
...
+                    match raw_event.deserialize() {
+                        Ok(AnySyncTimelineEvent::State(event)) => {
+                            // SAFETY: Casting `AnySyncTimelineEvent` to `AnySyncStateEvent` is safe
+                            // because we are indeed manipulating a state event.
```
Comment (jplatte) [inline crates/matrix-sdk-base/src/sliding_sync.rs:439]: "we checked that there is a `state_key`" would be more understandable, IMO.

File: crates/matrix-sdk-base/src/sliding_sync.rs [hunk 3]
```diff
@@ -402,6 +405,35 @@ impl BaseClient {
...
     }
+
+    pub(crate) fn deserialize_state_events_from_timeline(
+        raw_events: &[Raw<AnySyncTimelineEvent>],
+    ) -> Vec<(Raw<AnySyncStateEvent>, AnySyncStateEvent)> {
+        raw_events
+            .iter()
+            .filter_map(|raw_event| {
+                if raw_event.get_field::<serde::de::IgnoredAny>("state_key").is_ok() {
+                    match raw_event.deserialize() {
```
Comment (jplatte) [inline crates/matrix-sdk-base/src/sliding_sync.rs:436]: You can use `deserialize_as::<AnySyncStateEvent>()` here to avoid the unreachable branch.

**Review by jplatte — CHANGES_REQUESTED** [review]

File: crates/matrix-sdk-base/src/sliding_sync.rs (hunk 1 above)
Comment (Hywan) [reply crates/matrix-sdk-base/src/sliding_sync.rs]: Good catch, thanks.

File: crates/matrix-sdk-base/src/sliding_sync.rs (hunk 3 above)
Comment (Hywan) [reply crates/matrix-sdk-base/src/sliding_sync.rs]: Indeed, thanks!

File: crates/matrix-sdk-base/src/sliding_sync.rs (hunk 2 above)
Comment (Hywan) [reply crates/matrix-sdk-base/src/sliding_sync.rs]: :+1:

**Review by jplatte — APPROVED** [review]
